### PR TITLE
Fixed issue #8 in SwagLyrics repo (reading unsupported.txt from site-packages)

### PR DESCRIPTION
**Pull request by chriswang030**
I've created a config.py file for general global level variables, there I've added the site-packages directory path for unsupported.txt

cli.py and __main__.py now read/write from the site-packages unsupported.txt rather than creating a new one and updating that one in the local directory from which swaglyrics is run.

### CODE REVIEW

**Comment by adhv45** [comment]
it cannot write in site-packages folder, if not run with sudo access after install. I tried it and it spits following error.

Screenshot from 2019-03-29 18-12-34

**Comment by aadibajpai** [comment]
Looks okay but I'd like to ensure this works across all operating systems. Doesn't seem to work on Linux ^

**Comment by chriswang030** [comment]
@adhv45 is there any way to get around that? seems like we can't update the site-packages unsupported.txt unless the user installs with sudo access

**Comment by aadibajpai** [comment]
@chriswang030 I've set pep8speaks to ignore the tab in indentation error and have set maz line length to 120 characters so you needn't fix those 👍

**Comment by aadibajpai** [comment]
@chriswang030 so do you think you can get this working? I'd prefer to write to site-packages but if that's not possible I guess I'd have to go with the AppData option in #1085

**Comment by chriswang030** [comment]
Hey sorry, I've just been working on it on my local repo. I don't think there's a way to write to site-packages without sudo access from what I've tried right now. I'll commit some stuff tonight.

**Comment by aadibajpai** [comment]
So I found that `pip install --user` installs the package in the user directory which is accessible w/o root so that might be helpful but I'm not sure if we can leave that in their hands.

**Comment by adhv45** [comment]
But not everyone installs with --user permission. It will cause a problem there for the root permissions.

**Comment by aadibajpai** [comment]
> But not everyone installs with --user permission. It will cause a problem there for the root permissions.

yeah which is why I can't decide which approach to go with

**Pull request closed without merging**
