### PR TITLE
[IMPROVEMENT] Modern UI for Browser Viewer

### PR DESCRIPTION
**Pull request by sampoder**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [x] I have used the project briefly.

---

I was trialling this software and felt that the web version could be styled to look nicer so it is more inviting for newer users. It will also make it easier to use for some meaning they will use it more often. I am happy to adapt it to your liking but I feel this is a simple way to show the information that is more visually pleasing.

### CODE REVIEW

**Comment by aadibajpai** [comment]
Do you have a screenshot of how it looks now?

**Comment by sampoder** [comment]
Sorry, for being late. I know it's kind of basic, but if you have any improvements let me know! Thanks!
swaglyricuiscreenshot

**Comment by aadibajpai** [comment]
Your UI certainly looks good however, I feel the existing one does the job nicely. Great work though 👍

**Comment by sampoder** [comment]
Ok, no problem!

**Pull request closed without merging**
