### PR TITLE
[DOC] Pip usage for different distros 

### PR DESCRIPTION
**Pull request by hv7214**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Added a note to use pip in windows and pip3 in linux/macOs.

### CODE REVIEW

**Comment by hv7214** [comment]
@aadibajpai actually i triied to undo those *space trim* changes, but my editor forced to remove those spaces. okay, i will do it in normal editor(vim or so) and update the pr as soon as possiblesoon as possible.

**Comment by hv7214** [comment]
@aadibajpai why build is failing ? Should i open this as a issue, because i've just made some doc changes which doesn't relate to build means there is some preexisting problem.

**Comment by hv7214** [comment]
> Contains a bunch of unnecessary changes, you should update it to only reflect the changes you want to make :)

updated.

**Comment by aadibajpai** [comment]
I thought about this and this would probably be redundant because the installation instructions mention pip/pip3 stuff and I expected the person to read the whole document so I don't think we need to make it explicit everywhere.

**Pull request closed without merging**
