### PR TITLE
[FEATURE] Added GUI using eel library in python

### PR DESCRIPTION
**Pull request by anantha1999**
**[FEATURE]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**
- [x] I have used the project briefly.

---

I have added a very simple GUI using the eel library (more documentation regarding this can be found in https://github.com/samuelhwilliams/Eel). This was done as an idea for a GUI as a possible enhancement for the app was mentioned. I have kept the front end and the overall GUI very basic for now. If I should make any changes or if I went wrong somewhere please do let me know. The app can be found in the **/SwagLyrics-For-Spotify/swaglyrics/SwaglyricsGUI/SwagLyrics/dist** directory. As you can see I have put the entire changes in a new folder called **SwaglyricsGUI** and if any changes were made to the original files, I have reverted them back and if I haven't please do let me know. Thank you.

### CODE REVIEW

**Comment by aadibajpai** [comment]
Can you simplify your files changed? Like it shows 47 but most of them haven't really been changed.

**Comment by anantha1999** [comment]
> Can you simplify your files changed? Like it shows 47 but most of them haven't really been changed.
Sorry about the late reply. Yeah, I think I fixed this. Could you give it a look? Thank you!

**Comment by aadibajpai** [comment]
Can you give me a link to the exe to test?

**Comment by anantha1999** [comment]
> Can you give me a link to the exe to test?

The .exe file isn't getting pushed to the repo for some reason.
This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py

Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing

**Comment by aadibajpai** [comment]
> > Can you give me a link to the exe to test?
> 
> The .exe file isn't getting pushed to the repo for some reason.
> This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> 
> Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> The dist folder in the link contains the .exe file.

It's 290 Mb,I don't think that's viable

**Comment by anantha1999** [comment]
> > > Can you give me a link to the exe to test?
> > 
> > 
> > The .exe file isn't getting pushed to the repo for some reason.
> > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > The dist folder in the link contains the .exe file.
> 
> It's 290 Mb,I don't think that's viable
The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?

**Comment by aadibajpai** [comment]
> > > > Can you give me a link to the exe to test?
> > > 
> > > 
> > > The .exe file isn't getting pushed to the repo for some reason.
> > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > The dist folder in the link contains the .exe file.
> > 
> > 
> > It's 290 Mb,I don't think that's viable
> 
> The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?

Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit

**Comment by anantha1999** [comment]
> > > > > Can you give me a link to the exe to test?
> > > > 
> > > > 
> > > > The .exe file isn't getting pushed to the repo for some reason.
> > > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > > The dist folder in the link contains the .exe file.
> > > 
> > > 
> > > It's 290 Mb,I don't think that's viable
> > 
> > 
> > The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?
> 
> Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit

I tried decreasing the exe file size, but I wasn't able to. Will try some other method if possible. Any updates on the GUI?

**Comment by aadibajpai** [comment]
> > > > > > Can you give me a link to the exe to test?
> > > > > 
> > > > > 
> > > > > The .exe file isn't getting pushed to the repo for some reason.
> > > > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > > > The dist folder in the link contains the .exe file.
> > > > 
> > > > 
> > > > It's 290 Mb,I don't think that's viable
> > > 
> > > 
> > > The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?
> > 
> > 
> > Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit
> 
> Okay I reduced it to 40MB. So turns out, pandas and numpy files were getting adding too and that took up a lot of space. So I uninstalled them and then created the exe file. I have uploaded the files here https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing

I had tried the 290Mb exe and it didn't really run, do you think you could paste a few screenshots of your app?

**Comment by anantha1999** [comment]
> > > > > > > Can you give me a link to the exe to test?
> > > > > > 
> > > > > > 
> > > > > > The .exe file isn't getting pushed to the repo for some reason.
> > > > > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > > > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > > > > The dist folder in the link contains the .exe file.
> > > > > 
> > > > > 
> > > > > It's 290 Mb,I don't think that's viable
> > > > 
> > > > 
> > > > The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?
> > > 
> > > 
> > > Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit
> > 
> > 
> > Okay I reduced it to 40MB. So turns out, pandas and numpy files were getting adding too and that took up a lot of space. So I uninstalled them and then created the exe file. I have uploaded the files here https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> 
> I had tried the 290Mb exe and it didn't really run, do you think you could paste a few screenshots of your app?

It wasn't working for me also but I thought it was a system issue. But then I realized it had something to do with pyinstaller. So i reinstalled it from another source and created the exe file again and then it worked properly for me. So I think it's going to work for you as well.

**Comment by anantha1999** [comment]
> > > > > > > Can you give me a link to the exe to test?
> > > > > > 
> > > > > > 
> > > > > > The .exe file isn't getting pushed to the repo for some reason.
> > > > > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > > > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > > > > The dist folder in the link contains the .exe file.
> > > > > 
> > > > > 
> > > > > It's 290 Mb,I don't think that's viable
> > > > 
> > > > 
> > > > The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?
> > > 
> > > 
> > > Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit
> > 
> > 
> > Okay I reduced it to 40MB. So turns out, pandas and numpy files were getting adding too and that took up a lot of space. So I uninstalled them and then created the exe file. I have uploaded the files here https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> 
> I had tried the 290Mb exe and it didn't really run, do you think you could paste a few screenshots of your app?

I will upload the screenshots in the drive link I sent above? But give the exe file a shot, I am positive it's going to work now.

**Comment by anantha1999** [comment]
> > > > > > > > Can you give me a link to the exe to test?
> > > > > > > 
> > > > > > > 
> > > > > > > The .exe file isn't getting pushed to the repo for some reason.
> > > > > > > This is the file that needs to be run -> SwagLyrics-For-Spotify/SwaglyricsGUI/SwagLyrics/swaglyrics.py
> > > > > > > Since the .exe file is not getting recognized by git and hence I am not able to push it, I have uploaded the files in https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > > > > > > The dist folder in the link contains the .exe file.
> > > > > > 
> > > > > > 
> > > > > > It's 290 Mb,I don't think that's viable
> > > > > 
> > > > > 
> > > > > The exe file is created using pyinstaller, That's the minimum size possible I feel. Could you run the swaglyrics.py file and let me know if the gui is fine?
> > > > 
> > > > 
> > > > Nope, 290Mb wouldn't be feasible at all. I'll run the file and let you know in a bit
> > > 
> > > 
> > > Okay I reduced it to 40MB. So turns out, pandas and numpy files were getting adding too and that took up a lot of space. So I uninstalled them and then created the exe file. I have uploaded the files here https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing
> > 
> > 
> > I had tried the 290Mb exe and it didn't really run, do you think you could paste a few screenshots of your app?
> 
> I will upload the screenshots in the drive link I sent above? But give the exe file a shot, I am positive it's going to work now.

I have uploaded the screenshots in the drive link above.

**Comment by anantha1999** [comment]
I don't mean to rush, but any updates on this please?

**Comment by aadibajpai** [comment]
> I don't mean to rush, but any updates on this please? @aadibajpai

well, I saw the screenshots. The GUI looks nothing like how I was hoping it would be. I was looking for something like the terminal here https://camo.githubusercontent.com/cec44fc67f42a6d32e04e032c3f159845ffa68ed/68747470733a2f2f692e696d6775722e636f6d2f535252627862722e706e67 except as a GUI

**Comment by anantha1999** [comment]
> > I don't mean to rush, but any updates on this please? @aadibajpai
> 
> well, I saw the screenshots. The GUI looks nothing like how I was hoping it would be. I was looking for something like the terminal here https://camo.githubusercontent.com/cec44fc67f42a6d32e04e032c3f159845ffa68ed/68747470733a2f2f692e696d6775722e636f6d2f535252627862722e706e67 except as a GUI

I have changed the GUI to look similar to what you have shared. I have uploaded the executable file.
You can check it out here - https://drive.google.com/drive/folders/1UgVFKh9uFbBnLB9Hue0SdQFfBa5ZXAz5?usp=sharing

Please have a look @aadibajpai

**Comment by aadibajpai** [comment]
This one looks way better!

**Comment by anantha1999** [comment]
> This one looks way better!

Were you able to run the .exe file?

**Comment by anantha1999** [comment]
Also should I push the changes then?

**Comment by aadibajpai** [comment]
> > This one looks way better!
> 
> Were you able to run the .exe file?

I just looked at screenshots but I'll run the exe very soon

**Comment by aadibajpai** [comment]
closing, thank you for your effort!
see https://github.com/SwagLyrics/SwagLyricsGUI

**Pull request closed without merging**
