### PR TITLE
[Feature] Added System Tray App

### PR DESCRIPTION
**Pull request by sampoder**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [x] I have used the project briefly.

---

In the Readme.md, an area of improvement identified for Swag Lyrics was to add a system tray application for easy access to lyrics. I have implemented this using [Infi.Systray](https://github.com/Infinidat/infi.systray ) and Tkinter in Python. I did not use electron due to issues mentioned [here](https://github.com/SwagLyrics/SwagLyrics/issues/2). If this is not the best modules to use or what you envisioned let me know and I'd be willing to redo it. I have kept the design of the monospace theme of the project. Note: the reason "cureband" made commits is that I had GitHub desktop configured for when I was working on that project. I will be adding documentation in the next commit.

### CODE REVIEW

**Comment by sampoder** [comment]
Tests failed as unit tests need updating to new description.

**Comment by aadibajpai** [comment]
Do you have a screencast or something?

**Comment by sampoder** [comment]
> Do you have a screencast or something?

I'll share one when I get back from school (7 hrs to go) cause right now I'm on my mac

**Comment by sampoder** [comment]
For now I'm going to work on code coverage

**Comment by aadibajpai** [comment]
> For now I'm going to work on code coverage

First you should focus on the product then tests :)

**Comment by sampoder** [comment]
To-Do:

- [ ] Improve Aesthetics to be more cohesive with -- tab
- [ ] Package as .exe using either pyinstaller or other tool

**Comment by aadibajpai** [comment]
Is this ready to review?

**Comment by sampoder** [comment]
Yes, sorry I couldn't request a review.

**Comment by sampoder** [comment]
Still needs fixing on the code coverage but I can do that

**Comment by sampoder** [comment]
How can I work on this? I can't do GCI anymore this year for personal reasons but still wouldn't mind working on this.

**Comment by aadibajpai** [comment]
> How can I work on this? I can't do GCI anymore this year for personal reasons but still wouldn't mind working on this.

Sorry for the long wait, mate.

I was hoping for the app to be a standalone thing, as in, you don't necessarily need even python installed to make it work. I was wondering if that's possible?

**Comment by sampoder** [comment]
Hahahhaaa no problem...

I'll give that an explore I'm still on slack just a bit of a ghost

-- 
This email and any attachments are confidential and may also be privileged. 
If you have received this message in error, please (a) notify the sender 
immediately, (b) destroy this email and any attachments, and (c) do not 
use, copy, store and/or disclose to any person this email and any 
attachments. The sender gives no representation or guarantee with respect 
to the integrity of any emails or attached files and the recipient should 
check the integrity of and scan this email and any attached files for 
viruses prior to opening.

**Comment by aadibajpai** [comment]
> Hahahhaaa no problem... I'll give that an explore I'm still on slack just a bit of a ghost
> […](#)
> -- This email and any attachments are confidential and may also be privileged. If you have received this message in error, please (a) notify the sender immediately, (b) destroy this email and any attachments, and (c) do not use, copy, store and/or disclose to any person this email and any attachments. The sender gives no representation or guarantee with respect to the integrity of any emails or attached files and the recipient should check the integrity of and scan this email and any attached files for viruses prior to opening.

That would be awesome, I think if you bundle everything into a single file and run pyinstaller it might be possible. GUI should work 🤔

**Comment by sampoder** [comment]
Had a few things on going to be moving this over to a separate repo tonight and start working on it

**Comment by sampoder** [comment]
https://github.com/sampoder/SwagLyricsWindowsTrayApp

**Comment by aadibajpai** [comment]
> Had a few things on going to be moving this over to a separate repo tonight and start working on it

Sounds like a good idea, do you want to close this PR then?

**Comment by sampoder** [comment]
Ok, closing.

**Comment by aadibajpai** [comment]
> Ok, closing.

Oh also if you want then it doesn't necessarily have to exist in the tray. The primary principle is you get lyrics beautifully in just one click

**Pull request closed without merging**
